<?php
$msg['btn_repost']   = 'RePost';
$msg['csrf_title']   = 'Ticket error';
$msg['csrf_message'] = 'Ticket error. There was no ticket required for data transmission.<br />If you are not transmitting this data, there is possibility of a CSRF attack at the site which you accessed just before this.';
$msg['csrf_repost']  = 'However, a ticket error may take place, if a session cannot be continued or form is generated by JavaScript.<br />If correct for your having transmitted this data, please click "RePost" button.';
$msg['do_not_repost']= 'In addition, since it was not able to check that this request had been transmitted out of this site with the check of the referrer, retransmission of message cannot be performed.';
